# Generated by Django 4.2.4 on 2023-09-12 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='assets/images/blog-thumb-01.jpg', upload_to=''),
        ),
    ]
