# Generated by Django 4.2.4 on 2023-09-13 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_deneme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deneme',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
