# Generated by Django 4.2.4 on 2023-09-13 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_deneme_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Deneme',
        ),
    ]
