# Generated by Django 4.2.4 on 2023-09-14 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_about_us'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_info',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('deactive', 'Deactive')], default='active', max_length=100),
        ),
    ]
