# Generated by Django 4.2.4 on 2023-09-14 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_contact_info_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about_us',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('deactive', 'Deactive')], default='deactive', max_length=100),
        ),
        migrations.AlterField(
            model_name='contact_info',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('deactive', 'Deactive')], default='deactive', max_length=100),
        ),
    ]
