# Generated by Django 4.2.4 on 2023-09-14 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_about_us_status_alter_contact_info_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About_Us',
        ),
    ]
