# Generated by Django 4.2.4 on 2023-09-14 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_delete_about_us'),
    ]

    operations = [
        migrations.CreateModel(
            name='About_Us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_main', models.CharField(max_length=300)),
                ('text_main', models.TextField(max_length=3000)),
                ('header2', models.CharField(max_length=300)),
                ('text_2', models.TextField(max_length=3000)),
                ('header3', models.CharField(max_length=300)),
                ('text_3', models.TextField(max_length=3000)),
                ('header4', models.CharField(max_length=300)),
                ('text_4', models.TextField(max_length=3000)),
                ('header5', models.CharField(max_length=300)),
                ('text_5', models.TextField(max_length=3000)),
                ('header6', models.CharField(max_length=300)),
                ('text_6', models.TextField(max_length=3000)),
                ('header7', models.CharField(max_length=300)),
                ('text_7', models.TextField(max_length=3000)),
                ('header8', models.CharField(max_length=300)),
                ('text_8', models.TextField(max_length=3000)),
                ('header9', models.CharField(max_length=300)),
                ('text_9', models.TextField(max_length=3000)),
                ('header10', models.CharField(max_length=300)),
                ('text_10', models.TextField(max_length=3000)),
                ('status', models.CharField(choices=[('active', 'Active'), ('deactive', 'Deactive')], default='deactive', max_length=100)),
            ],
        ),
    ]
