# Generated by Django 4.2.4 on 2023-09-14 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_about_us'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='About_Us',
            new_name='AboutUs',
        ),
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name': 'AboutUs', 'verbose_name_plural': 'AboutUs'},
        ),
        migrations.AlterModelTable(
            name='aboutus',
            table='about_us',
        ),
    ]
