# Generated by Django 4.2.4 on 2023-09-14 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_rename_about_us_aboutus_alter_aboutus_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('creative-unique', 'Nature Lifestyle'), ('responsive-templates', 'Awesome Layouts'), ('creative-ideas', 'Creative Ideas'), ('awesome-layouts', 'Responsive Templates'), ('nature-lifestyle', 'Creative & Unique')], default='creative-unique', max_length=40),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=40),
        ),
    ]
