# Generated by Django 4.2.4 on 2023-09-21 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_alter_post_category_alter_post_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='confirmation',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('wait', 'Wait')], default='wait', max_length=40),
        ),
    ]
