# Generated by Django 4.2.4 on 2023-10-24 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, help_text='If blank, the slug will be generated automatically from the given title.', max_length=255, null=True, unique=True, verbose_name='slug'),
        ),
    ]
