# Generated by Django 4.2.4 on 2023-11-02 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_alter_post_slug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact_Info',
            new_name='ContactInfo',
        ),
        migrations.AlterModelOptions(
            name='contactinfo',
            options={'verbose_name': 'ContactInfo', 'verbose_name_plural': 'ContactInfo'},
        ),
        migrations.AlterModelOptions(
            name='support',
            options={},
        ),
        migrations.AlterModelTable(
            name='aboutus',
            table=None,
        ),
    ]
